import { cn } from '@/lib/utils';
import './globals.css';
import type {Metadata} from 'next';
import { montserratFont } from '@/lib/fonts';

export const metadata: Metadata = {
    title: 'Raiza Rahman',
    description: 'Generated by create next app'
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={cn('font-montserrat', montserratFont.variable)}>{children}</body>
        </html>
    );
}
